apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-writer
  namespace: proyecto2
spec:
  replicas: 1  # Ajusta a 2 para pruebas de rendimiento
  selector:
    matchLabels:
      app: kafka-writer
  template:
    metadata:
      labels:
        app: kafka-writer
    spec:
      containers:
      - name: kafka-writer
        image: 34.135.173.147.nip.io/proyecto2/kafka-writer:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-writer-service
  namespace: proyecto2
spec:
  ports:
  - port: 50052
    targetPort: 50052
  selector:
    app: kafka-writer