// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RabbitMQWriter_PublishMessage_FullMethodName = "/message.RabbitMQWriter/PublishMessage"
)

// RabbitMQWriterClient is the client API for RabbitMQWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Definición del servicio RabbitMQWriter
type RabbitMQWriterClient interface {
	PublishMessage(ctx context.Context, in *WeatherTweet, opts ...grpc.CallOption) (*PublishResponse, error)
}

type rabbitMQWriterClient struct {
	cc grpc.ClientConnInterface
}

func NewRabbitMQWriterClient(cc grpc.ClientConnInterface) RabbitMQWriterClient {
	return &rabbitMQWriterClient{cc}
}

func (c *rabbitMQWriterClient) PublishMessage(ctx context.Context, in *WeatherTweet, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, RabbitMQWriter_PublishMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RabbitMQWriterServer is the server API for RabbitMQWriter service.
// All implementations must embed UnimplementedRabbitMQWriterServer
// for forward compatibility.
//
// Definición del servicio RabbitMQWriter
type RabbitMQWriterServer interface {
	PublishMessage(context.Context, *WeatherTweet) (*PublishResponse, error)
	mustEmbedUnimplementedRabbitMQWriterServer()
}

// UnimplementedRabbitMQWriterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRabbitMQWriterServer struct{}

func (UnimplementedRabbitMQWriterServer) PublishMessage(context.Context, *WeatherTweet) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedRabbitMQWriterServer) mustEmbedUnimplementedRabbitMQWriterServer() {}
func (UnimplementedRabbitMQWriterServer) testEmbeddedByValue()                        {}

// UnsafeRabbitMQWriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RabbitMQWriterServer will
// result in compilation errors.
type UnsafeRabbitMQWriterServer interface {
	mustEmbedUnimplementedRabbitMQWriterServer()
}

func RegisterRabbitMQWriterServer(s grpc.ServiceRegistrar, srv RabbitMQWriterServer) {
	// If the following call pancis, it indicates UnimplementedRabbitMQWriterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RabbitMQWriter_ServiceDesc, srv)
}

func _RabbitMQWriter_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherTweet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RabbitMQWriterServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RabbitMQWriter_PublishMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RabbitMQWriterServer).PublishMessage(ctx, req.(*WeatherTweet))
	}
	return interceptor(ctx, in, info, handler)
}

// RabbitMQWriter_ServiceDesc is the grpc.ServiceDesc for RabbitMQWriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RabbitMQWriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.RabbitMQWriter",
	HandlerType: (*RabbitMQWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMessage",
			Handler:    _RabbitMQWriter_PublishMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
