apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-writer
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-writer
  template:
    metadata:
      labels:
        app: rabbitmq-writer
    spec:
      containers:
      - name: rabbitmq-writer
        image: 34.135.173.147.nip.io/proyecto2/rabbitmq-writer:latest
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-writer-service
  namespace: proyecto2
spec:
  selector:
    app: rabbitmq-writer
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051