// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: kafka_writer.proto

package kafka_writer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KafkaWriter_PublishMessage_FullMethodName = "/kafka_writer.KafkaWriter/PublishMessage"
)

// KafkaWriterClient is the client API for KafkaWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KafkaWriterClient interface {
	PublishMessage(ctx context.Context, in *WeatherTweet, opts ...grpc.CallOption) (*PublishResponse, error)
}

type kafkaWriterClient struct {
	cc grpc.ClientConnInterface
}

func NewKafkaWriterClient(cc grpc.ClientConnInterface) KafkaWriterClient {
	return &kafkaWriterClient{cc}
}

func (c *kafkaWriterClient) PublishMessage(ctx context.Context, in *WeatherTweet, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, KafkaWriter_PublishMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KafkaWriterServer is the server API for KafkaWriter service.
// All implementations must embed UnimplementedKafkaWriterServer
// for forward compatibility.
type KafkaWriterServer interface {
	PublishMessage(context.Context, *WeatherTweet) (*PublishResponse, error)
	mustEmbedUnimplementedKafkaWriterServer()
}

// UnimplementedKafkaWriterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKafkaWriterServer struct{}

func (UnimplementedKafkaWriterServer) PublishMessage(context.Context, *WeatherTweet) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedKafkaWriterServer) mustEmbedUnimplementedKafkaWriterServer() {}
func (UnimplementedKafkaWriterServer) testEmbeddedByValue()                     {}

// UnsafeKafkaWriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KafkaWriterServer will
// result in compilation errors.
type UnsafeKafkaWriterServer interface {
	mustEmbedUnimplementedKafkaWriterServer()
}

func RegisterKafkaWriterServer(s grpc.ServiceRegistrar, srv KafkaWriterServer) {
	// If the following call pancis, it indicates UnimplementedKafkaWriterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KafkaWriter_ServiceDesc, srv)
}

func _KafkaWriter_PublishMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherTweet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KafkaWriterServer).PublishMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KafkaWriter_PublishMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KafkaWriterServer).PublishMessage(ctx, req.(*WeatherTweet))
	}
	return interceptor(ctx, in, info, handler)
}

// KafkaWriter_ServiceDesc is the grpc.ServiceDesc for KafkaWriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KafkaWriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kafka_writer.KafkaWriter",
	HandlerType: (*KafkaWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishMessage",
			Handler:    _KafkaWriter_PublishMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kafka_writer.proto",
}
