version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      #GF_INSTALL_PLUGINS: "grafana-infinity-datasource"  # Instala el plugin Infinity
    ports:
      - "3000:3000"
    volumes:
      - ./:/data  # Monta el directorio actual dentro del contenedor en /data
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge