version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  # Puedes cambiar la contraseña
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana  # Volumen persistente para los datos
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
